services:
  - type: web
    name: medisense-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: GEMINI_API_KEY
        sync: false
