import React, { useState } from "react";
import { Stethoscope, FileText, Download, Printer, CheckCircle2 } from "lucide-react";
import { Button } from "../components/ui/Button";
import { generateDoctorSummaryPDF, printDoctorSummary } from "../utils/pdfGenerator";

export default function DoctorAssistant() {
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [summary, setSummary] = useState<any>(null);

  const handleDownloadPDF = () => {
    if (!summary) return;
    setDownloading(true);
    try {
      generateDoctorSummaryPDF(summary);
    } catch (e) {
      console.error("PDF generation error:", e);
    } finally {
      setTimeout(() => setDownloading(false), 800);
    }
  };

  const handlePrint = () => {
    if (!summary) return;
    printDoctorSummary(summary);
  };

  const generateSummary = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setSummary({
        patient: {
          name: "Ananya Sharma",
          age: 24,
          gender: "Female",
          bloodGroup: "O+",
        },
        concerns: ["Persistent mild headache for 2 days", "Occasional fatigue"],
        vitals: [
          { name: "Blood Pressure", value: "118/75 mmHg", trend: "Stable" },
          { name: "Heart Rate", value: "72 bpm", trend: "Stable" },
          { name: "SpO2", value: "98%", trend: "Normal" },
        ],
        medications: ["Metformin 500mg", "Vitamin D3 1000 IU"],
        reports: ["CBC & Lipid Profile (Oct 1) - LDL slightly elevated (115)"],
        questions: [
          "Could my headache be related to the new medication?",
          "Are there any specific lifestyle changes you recommend for my LDL level?",
        ]
      });
    }, 1500);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Doctor Visit Assistant</h1>
          <p className="text-muted-foreground mt-1">Generate a concise health summary for your upcoming appointment.</p>
        </div>
      </div>

      {!summary ? (
        <div className="bg-card border rounded-xl p-12 shadow-sm flex flex-col items-center justify-center text-center">
          <div className="bg-primary/10 p-4 rounded-full mb-4">
            <Stethoscope className="w-12 h-12 text-primary" />
          </div>
          <h3 className="text-xl font-semibold mb-2">Prepare for your next visit</h3>
          <p className="text-muted-foreground max-w-md mb-6">
            MediSense AI will compile your recent symptoms, vitals, medications, and uploaded reports into a clear, single-page summary for your doctor.
          </p>
          <Button size="lg" onClick={generateSummary} disabled={loading}>
            {loading ? "Generating Summary..." : "Generate Doctor Summary"}
          </Button>
        </div>
      ) : (
        <div className="bg-card border rounded-xl shadow-sm overflow-hidden">
          <div className="bg-primary/5 p-6 border-b flex justify-between items-center">
            <div className="flex items-center text-primary font-semibold text-lg">
              <FileText className="w-6 h-6 mr-2" /> Patient Summary
            </div>
            <div className="flex space-x-2">
              <Button variant="outline" size="sm" onClick={handlePrint}>
                <Printer className="w-4 h-4 mr-2" /> Print
              </Button>
              <Button size="sm" onClick={handleDownloadPDF} disabled={downloading}>
                <Download className="w-4 h-4 mr-2" /> {downloading ? "Generating PDF..." : "Download PDF"}
              </Button>
            </div>
          </div>
          
          <div className="p-8 space-y-8 bg-white dark:bg-card text-foreground">
            {/* Header */}
            <div className="flex justify-between items-start border-b pb-4">
              <div>
                <h2 className="text-2xl font-bold">{summary.patient.name}</h2>
                <p className="text-muted-foreground">{summary.patient.age} yrs • {summary.patient.gender} • Blood: {summary.patient.bloodGroup}</p>
              </div>
              <div className="text-right">
                <p className="font-medium">Date: {new Date().toLocaleDateString()}</p>
                <p className="text-sm text-muted-foreground">Generated by MediSense AI</p>
              </div>
            </div>

            {/* Content */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-6">
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Current Concerns</h3>
                  <ul className="list-disc pl-5 space-y-1">
                    {summary.concerns.map((c: string, i: number) => (
                      <li key={i} className="font-medium">{c}</li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Recent Vitals</h3>
                  <div className="bg-muted/50 rounded-lg p-4 space-y-2">
                    {summary.vitals.map((v: any, i: number) => (
                      <div key={i} className="flex justify-between">
                        <span className="text-muted-foreground">{v.name}</span>
                        <span className="font-medium">{v.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Current Medications</h3>
                  <ul className="list-disc pl-5 space-y-1">
                    {summary.medications.map((m: string, i: number) => (
                      <li key={i} className="font-medium">{m}</li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground mb-3">Recent Reports</h3>
                  <ul className="list-disc pl-5 space-y-1">
                    {summary.reports.map((r: string, i: number) => (
                      <li key={i} className="font-medium text-sm">{r}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            <div className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900 rounded-lg p-5">
              <h3 className="text-sm font-bold uppercase tracking-wider text-blue-800 dark:text-blue-300 mb-3">Suggested Questions for Doctor</h3>
              <ul className="list-disc pl-5 space-y-2 text-blue-900 dark:text-blue-100 font-medium">
                {summary.questions.map((q: string, i: number) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </div>
            
            <div className="pt-4 border-t text-center">
              <p className="text-xs text-muted-foreground">
                This summary was auto-generated from patient-reported data and AI analysis. It is for informational purposes and does not substitute a clinical evaluation.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
